[package]
name = "websocat4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytes = "1.5.0"
catty = "0.1.5"
futures = "0.3.28"
object-pool = "0.5.4"
rhai = { version = "1.16.2", features = ["serde", "internals", "sync", "no_custom_syntax", "no_float", "no_index", "no_time", "no_module", "no_optimize", "unchecked"] }
serde = { version = "1.0.188", features = ["derive"] }
sharded-slab = "0.1.7"
tokio = { version = "1.32.0", features = ["sync", "net", "rt", "macros", "io-util", "io-std"] }
